export const investment = [
    {
        image:"featuredimg3.jpg",
        price:"810,550",
        est:"7,250",
        title:"Residential",
        address:"Menchester city",
        bed:"1",
        bath:"2",
        furniture:"Equity ownership",
    },
    {
        image:"invest2.png",
        price:"4,025",
        est:"3,250",
        title:"Land",
        address:"Southfield Road, Oxford OX4",
        bed:"0",
        bath:"0",
        furniture:"Rentel Income",
    },
    {
        image:"featuredimg2.jpg",
        price:"6,250",
        est:"17,250",
        title:"Industrial",
        address:"Leeds city center",
        bed:"3",
        bath:"2",
        furniture:"Joined venture",
    },
    {
        image:"sale5.png",
        price:"345,450",
        est:"17,250",
        title:"Special purpose",
        address:"Derby side country ",
        bed:"3",
        bath:"2",
        furniture:"Rentel income",
    },
    {
        image:"sale4.png",
        price:"645,000",
        est:"7,250",
        title:"Residential",
        address:"Southfield Road, Oxford OX4",
        bed:"3",
        bath:"2",
        furniture:"join venture",
    },
    {
        image:"invest6.png",
        price:"20,000",
        est:"3,250",
        title:"Land",
        address:"Southfield Road, Oxford OX4",
        bed:"0",
        bath:"0",
        furniture:"join venture",
    },
    {
        image:"sale8.png",
        price:"125,000",
        est:"7,250",
        title:"Industrial",
        address:"Menchester city",
        bed:"3",
        bath:"2",
        furniture:"join venture",
    },
    {
        image:"invest8.png",
        price:"3,450",
        est:"17,250",
        title:"Land ",
        address:"Leeds city center",
        bed:"0",
        bath:"0",
        furniture:"Equity Ownership",
    },
    {
        image:"sale9.png",
        price:"800,000",
        est:"7,250",
        title:"Special Purpose",
        address:"Southfield Road, Oxford OX4",
        bed:"3",
        bath:"2",
        furniture:"Equity Ownership",
    },
   
   
   
   
   

]