export const sale = [
    {
        image:"featuredimg1.webp",
        price:"4,250",
        title:"Semi detached house",
        address:"Southfield Road, Oxford OX4",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"3",
        bath:"2",
        furniture:"semi-furnished",
    },
    {
        image:"featuredimg3.jpg",
        price:"654,250",
        title:"semi detached house",
        address:"Southfield Road, Oxford OX4",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"3",
        bath:"2",
        furniture:"semi-furnished",
    },
    {
        image:"featuredimg2.jpg",
        price:"926,250",
        title:"Bunglow",
        address:"Leeds city center",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"3",
        bath:"2",
        furniture:"semi-furnished",
    },
    {
        image:"sale4.png",
        price:"106,250",
        title:"Bunglow",
        address:"Derby side country ",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"4",
        bath:"4",
        furniture:"un-furnished",
    },
    {
        image:"sale5.png",
        price:"904,250",
        title:"semi detached house",
        address:"Southfield Road, Oxford OX4",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"3",
        bath:"2",
        furniture:"semi-furnished",
    },
    {
        image:"sale6.png",
        price:"336,250",
        title:"penthouse",
        address:"Menchester city",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"1",
        bath:"1",
        furniture:"semi-furnished",
    },
    {
        image:"sale7.png",
        price:"107,250",
        title:"Bunglow",
        address:"Leeds city center",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"4",
        bath:"4",
        furniture:"semi-furnished",
    },
    {
        image:"sale8.png",
        price:"829,250",
        title:"penthouse ",
        address:"Menchester city",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"1",
        bath:"2",
        furniture:"un-furnished",
    },
    {
        image:"sale9.png",
        price:"100,250",
        title:"Semi detached house",
        address:"Southfield Road, Oxford OX4",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        bed:"3",
        bath:"2",
        furniture:"semi-furnished",
    },
   
   
   
   
   

]