export const blog = [
    {
        img:"Blogimg1.jpg",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        title:"Which properties are selling best right now?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar.png",
        name:"Easy Hakkies",
        date:"june 21,2023",
    },
    {
        img:"Image.png",
        title:"What do higher intrest rates men for the housing market?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar2.png",
        name:"Amarchi stones",
        date:"june 21,2021",
    },
    {
        img:"blogimg3.webp",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blog3.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blogimage4.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blog5.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"featuredimg1.webp",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blog7.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blog8.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
    {
        img:"blog9.png",
        title:"The best area to live in north london?",
        desc:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo. Lorem ipsum dolor sit amet consectetur, adipisicing elit. Accusantium culpa qui ducimus inventore? A nostrum deserunt quidem. Dolore, voluptas blanditiis! Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis ipsum sunt totam nobis consectetur perspiciatis repellendus recusandae et. Perspiciatis, maiores?",
        para:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.",
        para1:"Lorem, ipsum dolor sit amet consectetur adipisicing elit. molestiae qui hic quis illo.  molestiae qui hic quis illo.",
        img1:"Avatar3.png",
        name:"Bruana Marcos",
        date:"Jan 19,2023",
    },
]